version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@3.0.0
workflows:
  build_test_deploy:
    jobs:
      - build
      - aws-ecr/build_and_push_image:
          repo: ${CIRCLE_PROJECT_REPONAME}
          requires:
            - build

  build_benchmark:
    jobs:
      - build
      - benchmark

jobs:

  build:
    machine: true
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run:
          name: Build the docker image
          command: docker build -t monero:$CIRCLE_SHA1 /home/circleci/project
